version: '3.8'

services:
  node-app:
    build: .
    image: node-app
    # environment:
    #   - MONGODB_URL=mongodb://mongodb:27017/test
    ports:
      - '8050:8050'
    depends_on:
      - mongodb
    volumes:
      - .:/src
    networks:
      - node-network

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge